package com.backend.happyhome.audit;

public enum AuditAction {

	LOGIN, LOGIN_SUCCESS, LOGIN_FAILED, CONSUMER_REGISTERED, VENDOR_REGISTERED, CONSUMER_REGISTRATION_FAILED,VENDOR_REGISTRATION_FAILED,SERVICE_CREATED, SERVICE_UPDATED, SERVICE_DELETED, BOOKING_CREATED, BOOKING_CANCELLED, PAYMENT_INITIATED, PAYMENT_SUCCESS, PAYMENT_FAILED
}
